<?php

function opcache_get_status(): array
{
    return [
        'opcache_enabled' => true,
        'cache_full' => false,
        'restart_pending' => false,
        'restart_in_progress' => false,
        'memory_usage' => [
            'used_memory' => 12028872,
            'free_memory' => 4235696,
            'wasted_memory' => 512648,
            'current_wasted_percentage' => 3.0556201934814,
        ],
        'interned_strings_usage' => [
            'buffer_size' => 8388608,
            'used_memory' => 4182056,
            'free_memory' => 4206552,
            'number_of_strings' => 35657,
        ],
        'opcache_statistics' => [
            'num_cached_scripts' => 59,
            'num_cached_keys' => 78,
            'max_cached_keys' => 223,
            'hits' => 66817,
            'start_time' => time() - 86400 * 12 - 3600 * 7,
            'last_restart_time' => 0,
            'misses' => 126,
            'blacklist_misses' => 0,
            'blacklist_miss_ratio' => 0,
            'opcache_hit_rate' => 99.81178017119,
            'oom_restarts' => 0,
            'manual_restarts' => 0,
            'hash_restarts' => 0,
        ],
        'jit' => [
            'enabled' => false,
            'on' => false,
            'kind' => 0,
            'opt_level' => 0,
            'opt_flags' => 0,
            'buffer_size' => 0,
            'buffer_free' => 0,
        ],
        'scripts' => [
            '/var/www/phpweb/manual/en/toc/faq.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/faq.inc',
                'hits' => 9,
                'memory_consumption' => 5680,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345905,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/downloads.php' => [
                'full_path' => '/var/www/phpweb/downloads.php',
                'hits' => 86,
                'memory_consumption' => 9488,
                'last_used' => 'Sat Mar 16 12:03:47 2013',
                'last_used_timestamp' => 1363460627,
                'timestamp' => 1355102402,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/languages.inc' => [
                'full_path' => '/var/www/phpweb/include/languages.inc',
                'hits' => 5605,
                'memory_consumption' => 16984,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1362994804,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/header.inc' => [
                'full_path' => '/var/www/phpweb/include/header.inc',
                'hits' => 9,
                'memory_consumption' => 20352,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1357938001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/getting-started.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/getting-started.inc',
                'hits' => 9,
                'memory_consumption' => 1936,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345409,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/faq.php' => [
                'full_path' => '/var/www/phpweb/manual/en/faq.php',
                'hits' => 122,
                'memory_consumption' => 5152,
                'last_used' => 'Sat Mar 16 12:06:15 2013',
                'last_used_timestamp' => 1363460775,
                'timestamp' => 1363345906,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/footer.inc' => [
                'full_path' => '/var/www/phpweb/include/footer.inc',
                'hits' => 9,
                'memory_consumption' => 1976,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/site.inc' => [
                'full_path' => '/var/www/phpweb/include/site.inc',
                'hits' => 5605,
                'memory_consumption' => 63488,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1354724402,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/mirrors.inc' => [
                'full_path' => '/var/www/phpweb/include/mirrors.inc',
                'hits' => 5605,
                'memory_consumption' => 96160,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363419613,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/refs.basic.vartype.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/refs.basic.vartype.inc',
                'hits' => 9,
                'memory_consumption' => 5032,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345844,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/layout.inc' => [
                'full_path' => '/var/www/phpweb/include/layout.inc',
                'hits' => 5605,
                'memory_consumption' => 145704,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1356610801,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/sites.php' => [
                'full_path' => '/var/www/phpweb/sites.php',
                'hits' => 73,
                'memory_consumption' => 2024,
                'last_used' => 'Sat Mar 16 12:10:10 2013',
                'last_used_timestamp' => 1363461010,
                'timestamp' => 1354724402,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/search.php' => [
                'full_path' => '/var/www/phpweb/search.php',
                'hits' => 3083,
                'memory_consumption' => 19728,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1347648005,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/langref.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/langref.inc',
                'hits' => 49,
                'memory_consumption' => 7416,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345411,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/index.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/index.inc',
                'hits' => 132,
                'memory_consumption' => 4680,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345409,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/docs.php' => [
                'full_path' => '/var/www/phpweb/docs.php',
                'hits' => 73,
                'memory_consumption' => 4536,
                'last_used' => 'Sat Mar 16 12:04:36 2013',
                'last_used_timestamp' => 1363460676,
                'timestamp' => 1347648000,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/shared-manual.inc' => [
                'full_path' => '/var/www/phpweb/include/shared-manual.inc',
                'hits' => 122,
                'memory_consumption' => 107688,
                'last_used' => 'Sat Mar 16 12:06:15 2013',
                'last_used_timestamp' => 1363460775,
                'timestamp' => 1357938001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/mozopensearch.inc' => [
                'full_path' => '/var/www/phpweb/include/mozopensearch.inc',
                'hits' => 14,
                'memory_consumption' => 1232,
                'last_used' => 'Sat Mar 16 12:00:34 2013',
                'last_used_timestamp' => 1363460434,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/ip-to-country.inc' => [
                'full_path' => '/var/www/phpweb/include/ip-to-country.inc',
                'hits' => 5605,
                'memory_consumption' => 21840,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/version.inc' => [
                'full_path' => '/var/www/phpweb/include/version.inc',
                'hits' => 775,
                'memory_consumption' => 7880,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363321202,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/errors.inc' => [
                'full_path' => '/var/www/phpweb/include/errors.inc',
                'hits' => 691,
                'memory_consumption' => 59888,
                'last_used' => 'Sat Mar 16 12:10:33 2013',
                'last_used_timestamp' => 1363461033,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/countries.inc' => [
                'full_path' => '/var/www/phpweb/include/countries.inc',
                'hits' => 5605,
                'memory_consumption' => 31184,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363419614,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/error.php' => [
                'full_path' => '/var/www/phpweb/error.php',
                'hits' => 691,
                'memory_consumption' => 61952,
                'last_used' => 'Sat Mar 16 12:10:33 2013',
                'last_used_timestamp' => 1363461033,
                'timestamp' => 1347648000,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/refs.basic.text.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/refs.basic.text.inc',
                'hits' => 9,
                'memory_consumption' => 3312,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345831,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/loadavg.inc' => [
                'full_path' => '/var/www/phpweb/include/loadavg.inc',
                'hits' => 3775,
                'memory_consumption' => 12184,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1354738801,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/prepend.inc' => [
                'full_path' => '/var/www/phpweb/include/prepend.inc',
                'hits' => 5605,
                'memory_consumption' => 23432,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/o.php' => [
                'full_path' => '/var/www/phpweb/o.php',
                'hits' => 1,
                'memory_consumption' => 13424,
                'last_used' => 'Sat Mar 16 18:11:21 2013',
                'last_used_timestamp' => 1363482681,
                'timestamp' => 1363482654,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/pregen-events.inc' => [
                'full_path' => '/var/www/phpweb/include/pregen-events.inc',
                'hits' => 1141,
                'memory_consumption' => 840,
                'last_used' => 'Sat Mar 16 12:15:07 2013',
                'last_used_timestamp' => 1363461307,
                'timestamp' => 1363419615,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/opcache.php' => [
                'full_path' => '/var/www/phpweb/opcache.php',
                'hits' => 0,
                'memory_consumption' => 13944,
                'last_used' => 'Sun Mar 17 01:22:31 2013',
                'last_used_timestamp' => 1363508551,
                'timestamp' => 1363508542,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/refs.calendar.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/refs.calendar.inc',
                'hits' => 9,
                'memory_consumption' => 2264,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345437,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/manual/en/toc/security.inc' => [
                'full_path' => '/var/www/phpweb/manual/en/toc/security.inc',
                'hits' => 19,
                'memory_consumption' => 5352,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363345419,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/pregen-news.inc' => [
                'full_path' => '/var/www/phpweb/include/pregen-news.inc',
                'hits' => 1161,
                'memory_consumption' => 57896,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363419615,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/my.php' => [
                'full_path' => '/var/www/phpweb/my.php',
                'hits' => 34,
                'memory_consumption' => 22640,
                'last_used' => 'Sat Mar 16 12:15:15 2013',
                'last_used_timestamp' => 1363461315,
                'timestamp' => 1354724402,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/pregen-confs.inc' => [
                'full_path' => '/var/www/phpweb/include/pregen-confs.inc',
                'hits' => 678,
                'memory_consumption' => 1400,
                'last_used' => 'Sat Mar 16 12:02:49 2013',
                'last_used_timestamp' => 1363460569,
                'timestamp' => 1363419615,
                'revalidate' => 0,
            ],
            '/var/www/index.php' => [
                'full_path' => '/var/www/index.php',
                'hits' => 1,
                'memory_consumption' => 744,
                'last_used' => 'Sat Mar 16 12:01:20 2013',
                'last_used_timestamp' => 1363460480,
                'timestamp' => 1358644238,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/index-stable.php' => [
                'full_path' => '/var/www/phpweb/index-stable.php',
                'hits' => 679,
                'memory_consumption' => 22208,
                'last_used' => 'Sat Mar 16 12:02:49 2013',
                'last_used_timestamp' => 1363460569,
                'timestamp' => 1347648003,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/conferences/index.php' => [
                'full_path' => '/var/www/phpweb/conferences/index.php',
                'hits' => 462,
                'memory_consumption' => 3872,
                'last_used' => 'Sat Mar 16 12:15:07 2013',
                'last_used_timestamp' => 1363461307,
                'timestamp' => 1347648000,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/support.php' => [
                'full_path' => '/var/www/phpweb/support.php',
                'hits' => 73,
                'memory_consumption' => 1912,
                'last_used' => 'Sat Mar 16 12:06:40 2013',
                'last_used_timestamp' => 1363460800,
                'timestamp' => 1347648005,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/op.php' => [
                'full_path' => '/var/www/phpweb/op.php',
                'hits' => 0,
                'memory_consumption' => 1448,
                'last_used' => 'Sun Mar 17 01:34:33 2013',
                'last_used_timestamp' => 1363509273,
                'timestamp' => 1363509263,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/posttohost.inc' => [
                'full_path' => '/var/www/phpweb/include/posttohost.inc',
                'hits' => 342,
                'memory_consumption' => 3824,
                'last_used' => 'Sat Mar 16 12:09:18 2013',
                'last_used_timestamp' => 1363460958,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/langchooser.inc' => [
                'full_path' => '/var/www/phpweb/include/langchooser.inc',
                'hits' => 5605,
                'memory_consumption' => 23784,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1347648001,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/manual-lookup.inc' => [
                'full_path' => '/var/www/phpweb/include/manual-lookup.inc',
                'hits' => 624,
                'memory_consumption' => 26648,
                'last_used' => 'Sat Mar 16 12:10:33 2013',
                'last_used_timestamp' => 1363461033,
                'timestamp' => 1354750802,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/mailing-lists.php' => [
                'full_path' => '/var/www/phpweb/mailing-lists.php',
                'hits' => 342,
                'memory_consumption' => 31576,
                'last_used' => 'Sat Mar 16 12:09:18 2013',
                'last_used_timestamp' => 1363460958,
                'timestamp' => 1361200802,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/last_updated.inc' => [
                'full_path' => '/var/www/phpweb/include/last_updated.inc',
                'hits' => 5605,
                'memory_consumption' => 840,
                'last_used' => 'Sat Mar 16 12:16:31 2013',
                'last_used_timestamp' => 1363461391,
                'timestamp' => 1363419675,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/include/email-validation.inc' => [
                'full_path' => '/var/www/phpweb/include/email-validation.inc',
                'hits' => 342,
                'memory_consumption' => 9168,
                'last_used' => 'Sat Mar 16 12:09:18 2013',
                'last_used_timestamp' => 1363460958,
                'timestamp' => 1362175205,
                'revalidate' => 0,
            ],
            '/var/www/phpweb/index.php' => [
                'full_path' => '/var/www/phpweb/index.php',
                'hits' => 679,
                'memory_consumption' => 1840,
                'last_used' => 'Sat Mar 16 12:02:49 2013',
                'last_used_timestamp' => 1363460569,
                'timestamp' => 1347648003,
                'revalidate' => 0,
            ],
        ],
    ];
}

function opcache_get_configuration(): array
{
    return [
        'directives' => [
            'opcache.enable' => true,
            'opcache.enable_cli' => false,
            'opcache.use_cwd' => true,
            'opcache.validate_timestamps' => true,
            'opcache.dups_fix' => false,
            'opcache.revalidate_path' => false,
            'opcache.log_verbosity_level' => 4,
            'opcache.memory_consumption' => 16777216,
            'opcache.interned_strings_buffer' => 8,
            'opcache.max_accelerated_files' => 200,
            'opcache.max_wasted_percentage' => 0.05,
            'opcache.consistency_checks' => 0,
            'opcache.force_restart_timeout' => 180,
            'opcache.revalidate_freq' => 0,
            'opcache.preferred_memory_model' => '',
            'opcache.blacklist_filename' => '/etc/zo_blacklist.txt',
            'opcache.max_file_size' => 0,
            'opcache.error_log' => '',
            'opcache.protect_memory' => false,
            'opcache.save_comments' => true,
            'opcache.enable_file_override' => false,
            'opcache.optimization_level' => 4294967295,
            'opcache.jit' => 'disable',
            'opcache.jit_buffer_size' => 0,
        ],
        'version' => [
            'version' => '8.4.0-dev',
            'opcache_product_name' => 'Zend OPcache',
        ],
        'blacklist' => [
            '/var/www/www.php.net/manual/es',
            '/var/www/www.php.net/manual/it',
            '/var/www/www.php.net/manual/bg',
            '/var/www/www.php.net/manual/fa',
            '/var/www/www.php.net/manual/fr',
            '/var/www/www.php.net/manual/kr',
            '/var/www/www.php.net/manual/pt_BR',
            '/var/www/www.php.net/manual/tr',
            '/var/www/www.php.net/manual/de',
            '/var/www/www.php.net/manual/ro',
            '/var/www/www.php.net/manual/ru',
            '/var/www/www.php.net/manual/zh',
            '/var/www/www.php.net/manual/ja',
            '/var/www/www.php.net/manual/pl',
            '/var/www/www.php.net/manual/sr',
        ],
    ];
}
